### ISSUE TITLE
eval_single_head flag not used

### ISSUE THREAD

**Issue by juntingzh** [facebookresearch/agem#1]
I am interested in seeing the performance of A-GEM and RWALK in the single-head evaluation setting. I noticed you have a eval_single_head flag but you don't really use it in train_task_sequence() or test_task_sequence().
Any plan or suggestions to fix this?
Thanks!

**Comment by arslan-chaudhry** [comment]
While it's quite trivial to do this for RWalk/ EWC/ PI with setting the `logit_mask` for all the heads to 1, it requires a bit of work to do that for A-GEM. I have removed the flag because we don't support it officially. That being said, a pull request supporting this functionality would be great (see if you want to do it).

**Comment by juntingzh** [comment]
@arslan-chaudhry Thanks for the suggestions, I am interested in doing so. I just want to confirm the details. 
In the single-head case: we should prune the output predictions for the classes we haven't learned so far. In both training and testing, we should set  `logit_mask[test_labels]= 1` instead of `logit_mask[:]= 1`. Am I understanding correctly?
BTW, based on your experience, how does RWalk/EWC/PI perform in the single-head setting? Currently I am getting very bad results for almost all the methods, wondering if I did something wrong.

**Comment by arslan-chaudhry** [comment]
Yes, your understanding of `logit_mask` is correct. 
Re the performance of RWalk/ EWC/ PI please see our paper (https://arxiv.org/abs/1801.10112). Note that in this paper we do multiple passes over the data whereas the default in A-GEM is to do a single pass over the data (which btw is the correct thing to do in continual learning).
