### ISSUE TITLE
Code for Imagenet

### ISSUE THREAD

**Issue by pclucas14** [facebookresearch/agem#2]
Hi, 

I would like to reproduce your results for mini Imagenet; is there a main file I should use ? 

Thanks for making your code public, it's greatly appreciated!

-Lucas

**Comment by arslan-chaudhry** [comment]
We do not provide the script for mini Imagenet. Once you download the mini Imagenet dataset, you can edit the `conv_split_cifar.py` file to run the mini Imagenet experiments. The setup is the same as that of Split CIFAR; a total of 100 classes split into 20 tasks with 5 classes per task. The hyper-parameters for mini Imagenet are given in the appendix of https://arxiv.org/abs/1902.10486.

**Comment by pclucas14** [comment]
Hi, 

I was especially curious about how the preprocess the images. Are you resizing them  ? and / or normalizing them ?

Thanks!

**Comment by pclucas14** [comment]
Thanks for your answer. I would like to make sure my preprocessing is the same as yours. I see that you have shared code to load imagenet, all that's missing is the `.pkl` file you used. Could you point me towards the download link you used (or upload the `.pkl` file to the repository) ?

**Comment by arslan-chaudhry** [comment]
You can download the miniImageNet dataset (pickle file) from here: https://www.dropbox.com/s/yt3akdfchuafk25/miniImageNet_full.pickle?dl=0

Hope that helps!

**Comment by pclucas14** [comment]
Thanks for sharing. It seems there was some preprocessing done from the link you shared (1 pickle with 84 x 84 images) to the one used in your code [here]( https://github.com/facebookresearch/agem/blob/master/utils/data_utils.py#L844) (4 pickles, 224 x 224 images, train and test already split). 

I guess the only information I'm missing now is 
1) how to split train and test
2) if you could confirm you did resize to 224 x 224 (and if you used data augmentation)

**Comment by arslan-chaudhry** [comment]
The code for imageNet utils in the repository is outdated. I used 84 x 84 images. The train/ test split is 500/ 100 for each class. You can modify the cifar utils for imageNet.

**Comment by pclucas14** [comment]
great! closing the issue
